### ISSUE TITLE
Lots of console logs in YieldMath tests

### ISSUE THREAD

**Issue by uivlis** [yieldprotocol/yieldspace-v2#113]
For example, are [these](https://github.com/yieldprotocol/yieldspace-v2/blob/69379de0fbadc9c4b4d56c1057c0fee8f0fc40e3/test/013_yield_math_surface.ts#L78) intentional, or just debugging leftovers @albertocuestacanada ?

**Comment by albertocuestacanada** [comment]
They are debugging remnants. You can comment them, remove them, or set something so that they only print with a --debug flag passed on to hardhat, if you know how to do that. Up to you.
