### ISSUE TITLE
Implement invariant calculation function in YieldMath.sol

### ISSUE THREAD

**Issue by alcueca** [yieldprotocol/yieldspace-v2#127]
Add this, with a little clean-up: https://github.com/yieldprotocol/yieldspace-v1/blob/f4e728a59dd6c78b83c51c43a2f50cd8cb944d99/contracts/invariants/WhitepaperInvariant.sol#L124

**Comment by albertocuestacanada** [comment]
[Here](https://github.com/yieldprotocol/yieldspace-v2/pull/133)
